_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Demo:index }

_login:
    resource: "@TooterBundle/Controller/IndexController.php"
    type:     annotation

_profile:
    resource: "@TooterBundle/Controller/ProfileController.php"
    type:     annotation

_reset_password:
    resource: "@TooterBundle/Controller/PasswordController.php"
    type:     annotation

_reset_password_msg:
    resource: "@TooterBundle/Controller/PasswordController.php"
    type:     annotation

_sign_up:
    resource: "@TooterBundle/Controller/SignUpController.php"
    type:     annotation

_tooter:
    resource: "@TooterBundle/Controller/TootController.php"
    type:     annotation

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
